import { Form, useActionData, useLoaderData, useNavigation } from "react-router-dom";
import { useState } from "react";
import { calculateTax, formatCurrency, formatPercent } from "../utils/taxCalculator";

function Metric({ label, value, accent }) { return <div className={`tax-metric ${accent || ""}`}><span>{label}</span><strong>{value}</strong></div>; }

export default function Calculator() {
  const { brackets, jurisdictions, demo } = useLoaderData();
  const actionData = useActionData();
  const navigation = useNavigation();
  const [grossIncome, setGrossIncome] = useState(85000);
  const [filingStatus, setFilingStatus] = useState("single");
  const result = calculateTax({ grossIncome, filingStatus, brackets });
  const calculation = { jurisdiction_id: jurisdictions[0]?.id, filing_status: filingStatus, gross_income: result.grossIncome, total_tax: result.totalTax, effective_rate: result.effectiveRate, marginal_rate: result.marginalRate };

  return <div className="tax-page"><div className="tax-intro"><div><p className="tax-kicker">Personal tax planning</p><h1>Know your number.</h1><p>Explore how each dollar of income moves through the 2025 federal brackets.</p></div><div className="tax-status"><span className={demo ? "status-dot demo" : "status-dot"} />{demo ? "Demo data" : "Live Supabase data"}</div></div><section className="tax-calculator-grid"><div className="tax-card tax-form-card"><p className="tax-kicker">Your inputs</p><h2>Set your income</h2><label>Gross annual income<input type="number" min="0" step="1000" value={grossIncome} onChange={(event) => setGrossIncome(event.target.value)} /></label><label>Filing status<select value={filingStatus} onChange={(event) => setFilingStatus(event.target.value)}><option value="single">Single</option><option value="married_joint">Married filing jointly</option></select></label><div className="tax-note">This estimate models federal income tax only. It does not include deductions, credits, payroll taxes, or state taxes.</div></div><div className="tax-card tax-result-card"><div className="tax-result-heading"><div><p className="tax-kicker">Estimated outcome</p><h2>{formatCurrency(result.totalTax)} tax owed</h2></div><span>on {formatCurrency(result.grossIncome)}</span></div><div className="tax-metrics"><Metric label="Effective rate" value={formatPercent(result.effectiveRate)} accent="green" /><Metric label="Marginal rate" value={formatPercent(result.marginalRate)} accent="orange" /><Metric label="After federal tax" value={formatCurrency(result.netIncome)} /></div><div className="tax-breakdown"><div className="tax-breakdown-header"><span>Income by bracket</span><span>{result.breakdown.length} brackets reached</span></div>{result.breakdown.map((bracket) => <div className="tax-bar-row" key={bracket.id}><div className="tax-bar-label"><span>{formatPercent(Number(bracket.rate))} bracket</span><strong>{formatCurrency(bracket.tax)}</strong></div><div className="tax-bar-track"><div className="tax-bar-fill" style={{ width: `${Math.max(4, bracket.share * 100)}%` }} /></div><small>{formatCurrency(bracket.taxableIncome)} of income</small></div>)}</div></div></section><div className="tax-save-row"><Form method="post"><input type="hidden" name="calculation" value={JSON.stringify(calculation)} /><input name="name" placeholder="Name this calculation" aria-label="Calculation name" /><button type="submit" disabled={navigation.state === "submitting"}>{navigation.state === "submitting" ? "Saving..." : "Save calculation"}</button></Form>{actionData?.error && <span className="tax-error">{actionData.error}</span>}{actionData?.saved && <span className="tax-success">Calculation saved.</span>}</div></div>;
}