-- Run this once in the Supabase SQL Editor.
create table if not exists public.departments (
  id bigint generated by default as identity primary key,
  name varchar(100) not null,
  description text,
  created_by bigint references public.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint departments_name_unique unique (name)
);

create index if not exists departments_name_idx on public.departments (name);

alter table public.departments enable row level security;

-- The backend uses the Supabase service role key, so API authorization remains
-- in server/Routes/adminRoute.js and these policies protect direct client access.
drop policy if exists "Authenticated users can read departments" on public.departments;
create policy "Authenticated users can read departments"
  on public.departments for select
  to authenticated
  using (true);

drop policy if exists "Authenticated users can create departments" on public.departments;
create policy "Authenticated users can create departments"
  on public.departments for insert
  to authenticated
  with check (true);