create table if not exists public.departments (
  id bigint generated by default as identity primary key,
  name varchar(100) not null,
  description text,
  created_by bigint references public.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint departments_name_unique unique (name)
);

create table if not exists public.employees (
  user_id bigint primary key references public.users(id) on delete cascade,
  first_name varchar(100) not null,
  last_name varchar(100) not null,
  date_of_birth date not null,
  sex varchar(30) not null check (sex in ('female', 'male', 'other', 'prefer_not_to_say')),
  qualification varchar(200),
  department varchar(100),
  basic_pay numeric(14, 2) not null default 0 check (basic_pay >= 0),
  profile_image text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.employees
  add column if not exists department_id bigint references public.departments(id) on delete set null;

create index if not exists employees_department_id_idx
  on public.employees (department_id);

-- Backfill legacy text departments when names match exactly.
update public.employees employees
set department_id = departments.id
from public.departments departments
where employees.department_id is null
  and employees.department = departments.name;
