-- Employees are payroll profiles. A profile may optionally have a software login.
alter table public.employees
  add column if not exists id bigint generated by default as identity;

alter table public.employees
  drop constraint if exists employees_pkey;

alter table public.employees
  add constraint employees_pkey primary key (id);

alter table public.employees
  alter column user_id drop not null;

alter table public.employees
  drop constraint if exists employees_user_id_fkey;

alter table public.employees
  add constraint employees_user_id_fkey
  foreign key (user_id) references public.users(id) on delete set null;

alter table public.employees
  drop constraint if exists employees_user_id_key;

alter table public.employees
  add constraint employees_user_id_key unique (user_id);

-- Existing payroll entries stored the linked users.id. Convert them to employees.id.
alter table public.payroll_entries
  drop constraint if exists payroll_entries_employee_id_fkey;

update public.payroll_entries as payroll_entry
set employee_id = employee.id
from public.employees as employee
where employee.user_id = payroll_entry.employee_id;

alter table public.payroll_entries
  add constraint payroll_entries_employee_id_fkey
  foreign key (employee_id) references public.employees(id) on delete restrict;

create index if not exists employees_user_id_idx on public.employees(user_id);