create table if not exists public.customer_invoices (
  id bigint generated by default as identity primary key,
  customer_id bigint not null references public.customers(id) on delete restrict,
  invoice_number varchar(100) not null,
  invoice_date date not null default current_date,
  receivable_account_id bigint not null references public.ledger_accounts(id) on delete restrict,
  currency varchar(10) not null default 'GHS',
  exchange_rate numeric(14, 6) not null default 1 check (exchange_rate > 0),
  total_amount numeric(14, 2) not null check (total_amount > 0),
  customer_message text,
  memo text,
  status varchar(20) not null default 'open' check (status in ('draft', 'open', 'paid', 'void')),
  created_by bigint references public.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint customer_invoices_customer_number_unique unique (customer_id, invoice_number)
);

create table if not exists public.customer_invoice_lines (
  id bigint generated by default as identity primary key,
  customer_invoice_id bigint not null references public.customer_invoices(id) on delete cascade,
  line_number integer not null check (line_number > 0),
  item varchar(200),
  description text,
  quantity numeric(14, 4) not null check (quantity > 0),
  rate numeric(14, 2) not null check (rate >= 0),
  amount numeric(14, 2) not null check (amount > 0),
  created_at timestamptz not null default now(),
  constraint customer_invoice_lines_line_unique unique (customer_invoice_id, line_number)
);

create index if not exists customer_invoices_customer_date_idx
  on public.customer_invoices(customer_id, invoice_date desc);

create index if not exists customer_invoices_date_idx
  on public.customer_invoices(invoice_date desc);

create index if not exists customer_invoice_lines_invoice_idx
  on public.customer_invoice_lines(customer_invoice_id, line_number);
