create table if not exists public.supplier_bills (
  id bigint generated by default as identity primary key,
  supplier_id bigint not null references public.suppliers(id) on delete restrict,
  document_type varchar(10) not null default 'bill' check (document_type in ('bill', 'credit')),
  reference varchar(100),
  bill_date date not null default current_date,
  due_date date,
  payment_terms varchar(50),
  currency varchar(10) not null default 'GHS',
  subtotal numeric(14, 2) not null default 0 check (subtotal >= 0),
  discount_amount numeric(14, 2) not null default 0 check (discount_amount >= 0),
  tax_amount numeric(14, 2) not null default 0 check (tax_amount >= 0),
  total_amount numeric(14, 2) not null check (total_amount >= 0),
  bill_received boolean not null default true,
  memo text,
  created_by bigint references public.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.supplier_bill_lines (
  id bigint generated by default as identity primary key,
  supplier_bill_id bigint not null references public.supplier_bills(id) on delete cascade,
  ledger_account_id bigint not null references public.ledger_accounts(id) on delete restrict,
  amount numeric(14, 2) not null check (amount > 0),
  memo text,
  created_at timestamptz not null default now()
);

create index if not exists supplier_bills_supplier_date_idx
  on public.supplier_bills(supplier_id, bill_date desc);

create index if not exists supplier_bills_due_date_idx
  on public.supplier_bills(due_date);

create index if not exists supplier_bill_lines_bill_idx
  on public.supplier_bill_lines(supplier_bill_id);

create index if not exists supplier_bill_lines_account_idx
  on public.supplier_bill_lines(ledger_account_id);
