create table if not exists public.ledger_accounts (
  id bigint generated by default as identity primary key,
  code varchar(30) not null unique,
  name varchar(150) not null,
  account_type varchar(30) not null check (account_type in ('asset', 'liability', 'equity', 'income', 'expense')),
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.suppliers (
  id bigint generated by default as identity primary key,
  name varchar(200) not null,
  email varchar(200),
  phone varchar(50),
  address text,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create index if not exists ledger_accounts_active_idx on public.ledger_accounts(is_active, name);
create index if not exists suppliers_active_idx on public.suppliers(is_active, name);

insert into public.ledger_accounts (code, name, account_type)
values
  ('1000', 'Cash / bank', 'asset'),
  ('5100', 'Office supplies', 'expense'),
  ('5200', 'Software subscriptions', 'expense'),
  ('5300', 'Professional fees', 'expense'),
  ('5400', 'Utilities', 'expense'),
  ('5500', 'Travel and meals', 'expense'),
  ('2100', 'PAYE payable', 'liability'),
  ('2110', 'SSNIT payable', 'liability'),
  ('2120', 'Tier 2 payable', 'liability'),
  ('2130', 'Net wages payable', 'liability')
on conflict (code) do nothing;
