create table if not exists public.customers (
  id bigint generated by default as identity primary key,
  name varchar(200) not null,
  email varchar(200),
  phone varchar(50),
  address text,
  is_active boolean not null default true,
  created_by bigint references public.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists customers_active_idx on public.customers(is_active, name);
