create table if not exists public.journal_entries (
  id bigint generated by default as identity primary key,
  entry_date date not null default current_date,
  reference varchar(100),
  description text,
  source varchar(30) not null default 'manual' check (source in ('manual', 'cheque', 'cash', 'bank_transfer', 'payroll')),
  status varchar(20) not null default 'posted' check (status in ('draft', 'posted', 'void')),
  created_by bigint references public.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.journal_lines (
  id bigint generated by default as identity primary key,
  journal_entry_id bigint not null references public.journal_entries(id) on delete cascade,
  account varchar(150) not null,
  debit numeric(14, 2) not null default 0 check (debit >= 0),
  credit numeric(14, 2) not null default 0 check (credit >= 0),
  memo text,
  check (not (debit > 0 and credit > 0)),
  check (debit > 0 or credit > 0)
);

create table if not exists public.payment_records (
  id bigint generated by default as identity primary key,
  journal_entry_id bigint not null references public.journal_entries(id) on delete restrict,
  payment_type varchar(20) not null check (payment_type in ('cheque', 'cash', 'bank_transfer')),
  payment_number varchar(100),
  payment_date date not null default current_date,
  payee varchar(200) not null,
  bank_account varchar(150),
  amount numeric(14, 2) not null check (amount > 0),
  memo text,
  created_by bigint references public.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists journal_entries_date_idx on public.journal_entries(entry_date desc);
create index if not exists journal_lines_entry_idx on public.journal_lines(journal_entry_id);
create index if not exists payment_records_date_idx on public.payment_records(payment_date desc);
