create table if not exists public.payroll_runs (
  id bigint generated by default as identity primary key,
  period_start date not null,
  period_end date not null,
  status varchar(20) not null default 'draft' check (status in ('draft', 'processed', 'paid')),
  currency varchar(3) not null default 'GHS',
  ssnit_employee_rate numeric(6, 5) not null default 0.055,
  tier2_employee_rate numeric(6, 5) not null default 0,
  ssnit_employer_rate numeric(6, 5) not null default 0.13,
  tier2_employer_rate numeric(6, 5) not null default 0.05,
  total_gross numeric(14, 2) not null default 0,
  total_paye numeric(14, 2) not null default 0,
  total_employee_deductions numeric(14, 2) not null default 0,
  total_net numeric(14, 2) not null default 0,
  total_employer_contributions numeric(14, 2) not null default 0,
  total_employer_cost numeric(14, 2) not null default 0,
  created_by bigint references public.users(id) on delete set null,
  created_at timestamptz not null default now(),
  check (period_end >= period_start)
);

create table if not exists public.payroll_entries (
  id bigint generated by default as identity primary key,
  payroll_run_id bigint not null references public.payroll_runs(id) on delete cascade,
  employee_id bigint not null references public.users(id) on delete restrict,
  basic_pay numeric(14, 2) not null check (basic_pay >= 0),
  allowance numeric(14, 2) not null default 0 check (allowance >= 0),
  gross_pay numeric(14, 2) not null default 0,
  ssnit_employee numeric(14, 2) not null default 0,
  tier2_employee numeric(14, 2) not null default 0,
  paye numeric(14, 2) not null default 0,
  total_employee_deductions numeric(14, 2) not null default 0,
  net_pay numeric(14, 2) not null default 0,
  ssnit_employer numeric(14, 2) not null default 0,
  tier2_employer numeric(14, 2) not null default 0,
  total_employer_contributions numeric(14, 2) not null default 0,
  employer_cost numeric(14, 2) not null default 0,
  created_at timestamptz not null default now(),
  unique (payroll_run_id, employee_id)
);

create index if not exists payroll_entries_employee_id_idx on public.payroll_entries(employee_id);
create index if not exists payroll_runs_period_start_idx on public.payroll_runs(period_start);