create table if not exists public.cash_bank_accounts (
  id bigint generated by default as identity primary key,
  ledger_account_id bigint not null references public.ledger_accounts(id) on delete restrict,
  account_name varchar(150) not null,
  account_number varchar(100),
  bank_name varchar(150),
  account_type varchar(20) not null check (account_type in ('cash', 'bank')),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  unique (ledger_account_id),
  unique (account_name)
);

alter table public.payment_records
  add column if not exists cash_bank_account_id bigint references public.cash_bank_accounts(id) on delete restrict;

create index if not exists cash_bank_accounts_active_idx
  on public.cash_bank_accounts(is_active, account_name);

create index if not exists payment_records_cash_bank_account_idx
  on public.payment_records(cash_bank_account_id);

insert into public.cash_bank_accounts (ledger_account_id, account_name, account_type)
select id, name, 'cash'
from public.ledger_accounts
where code = '1000'
on conflict (ledger_account_id) do nothing;
